"""
Warehouse Capacity Risk + Forecast Drift Alerts
Detects warehouses nearing/exceeding physical capacity, and converts
the drift monitoring report into an actionable alert. Appends both
to the existing alerts.csv from the risk engine.
"""

import pandas as pd
import os

CAPACITY_WARNING_THRESHOLD = 0.85  # 85% of capacity = warning
CAPACITY_CRITICAL_THRESHOLD = 0.95  # 95% of capacity = critical


def detect_warehouse_capacity_risk():
    inventory_plan = pd.read_csv("data/processed/inventory_plan.csv")
    warehouses = pd.read_csv("data/raw/warehouses.csv")

    utilization = (
        inventory_plan.groupby("warehouse_id")["current_stock"].sum().reset_index()
        .rename(columns={"current_stock": "total_stock"})
    )
    utilization = utilization.merge(warehouses, on="warehouse_id", how="left")
    utilization["utilization_pct"] = (utilization["total_stock"] / utilization["capacity_units"]).round(4)

    utilization["capacity_status"] = pd.cut(
        utilization["utilization_pct"],
        bins=[-1, CAPACITY_WARNING_THRESHOLD, CAPACITY_CRITICAL_THRESHOLD, 999],
        labels=["HEALTHY", "WARNING", "CRITICAL"]
    )

    os.makedirs("data/processed", exist_ok=True)
    utilization.to_csv("data/processed/warehouse_utilization.csv", index=False)
    return utilization


def build_capacity_and_drift_alerts(utilization_df):
    alerts = []

    for _, row in utilization_df.iterrows():
        if row["capacity_status"] == "CRITICAL":
            alerts.append({
                "product_id": "N/A", "warehouse_id": row["warehouse_id"],
                "alert_type": "WAREHOUSE_CAPACITY_RISK", "severity": "HIGH",
                "message": f"Warehouse at {row['utilization_pct']*100:.1f}% capacity."
            })
        elif row["capacity_status"] == "WARNING":
            alerts.append({
                "product_id": "N/A", "warehouse_id": row["warehouse_id"],
                "alert_type": "WAREHOUSE_CAPACITY_RISK", "severity": "MEDIUM",
                "message": f"Warehouse at {row['utilization_pct']*100:.1f}% capacity, approaching limit."
            })

    # Forecast drift alert -- reads the drift report generated by drift_monitoring.py
    try:
        drift_df = pd.read_csv("reports/drift_report.csv")
        n_drifted = drift_df["drifted"].sum()
        n_total = len(drift_df)
        ratio = n_drifted / n_total if n_total else 0

        if ratio > 0.15:
            alerts.append({
                "product_id": "N/A", "warehouse_id": "ALL",
                "alert_type": "FORECAST_DRIFT", "severity": "HIGH",
                "message": f"{n_drifted}/{n_total} features drifted ({ratio:.1%}). Model retraining recommended/triggered."
            })
    except FileNotFoundError:
        pass  # drift_monitoring.py not run yet

    return pd.DataFrame(alerts)


def main():
    utilization = detect_warehouse_capacity_risk()
    print("Warehouse utilization:")
    print(utilization[["warehouse_id", "utilization_pct", "capacity_status"]].to_string(index=False))

    new_alerts = build_capacity_and_drift_alerts(utilization)

    # merge into existing alerts.csv
    existing_alerts = pd.read_csv("data/processed/alerts.csv")
    combined = pd.concat([existing_alerts, new_alerts], ignore_index=True)
    combined.to_csv("data/processed/alerts.csv", index=False)

    print(f"\nAdded {len(new_alerts)} new alerts (capacity + drift).")
    print(f"Total alerts now: {len(combined)}")


if __name__ == "__main__":
    main()